### ISSUE TITLE
Tarea: HU00 - Pagina Login

### ISSUE THREAD

**Issue by Hernan-martinezd** [luismh92/misw4203-2024-12-ingenieria-de-software-para-aplicaciones-moviles#1]
Responsable: [Christian Camilo Peña Florez](https://github.com/camilo2307)
Fecha entrega: 04-04-2024
Tiempo Estimado: 1 hora

**Comment by CamiloCastro-23** [comment]
Historia de Usuario terminada, con ambos roles de inicio de sesion y navegacion de pantallas

![Image](https://github.com/luismh92/misw4203-2024-12-ingenieria-de-software-para-aplicaciones-moviles/assets/141591369/a74fcde3-1100-4378-9936-d1b56f2e039b)
