### ISSUE TITLE
Tarea: HU01 - Consultar catalago de albumes

### ISSUE THREAD

**Issue by Hernan-martinezd** [luismh92/misw4203-2024-12-ingenieria-de-software-para-aplicaciones-moviles#2]
Responsable: [Camilo Castro Sanchez](https://github.com/CamiloCastro-MISO)
Fecha entrega: 04-04-2024
Tiempo Estimado: 4 horas

**Comment by CamiloCastro-23** [comment]
Historia de Usuario terminada, con el listado de albumes conectandose a la API del back en AWS

![Image](https://github.com/luismh92/misw4203-2024-12-ingenieria-de-software-para-aplicaciones-moviles/assets/141591369/4dd56599-9ba8-4618-99cb-762f2bc25f9d)
