### ISSUE TITLE
Tarea: HU02 - Consultar la informacion detallada de un album

### ISSUE THREAD

**Issue by Hernan-martinezd** [luismh92/misw4203-2024-12-ingenieria-de-software-para-aplicaciones-moviles#3]
Responsable:  [Camilo Castro Sanchez](https://github.com/CamiloCastro-MISO), [Christian Camilo Peña Florez](https://github.com/camilo2307)
Fecha entrega: 04-04-2024
Tiempo Estimado: 1 hora

**Comment by CamiloCastro-23** [comment]
Hu terminada y en la rama main
