### ISSUE TITLE
Tarea: HU04 - Consultar la información detallada de un ártista

### ISSUE THREAD

**Issue by Hernan-martinezd** [luismh92/misw4203-2024-12-ingenieria-de-software-para-aplicaciones-moviles#5]
Responsable: [Luis Alberto Mendoza Hernandez](https://github.com/luismh92), [Hernan David Martinez Dominguez](https://github.com/Hernan-martinezd) 
Fecha entrega: 04-04-2024
Tiempo Estimado: 1 hora

**Comment by CamiloCastro-23** [comment]
hu implementada y se encuentra en la rama master
