### ISSUE TITLE
Tarea: HU06 - Consultar la información detallada de coleccionista

### ISSUE THREAD

**Issue by Hernan-martinezd** [luismh92/misw4203-2024-12-ingenieria-de-software-para-aplicaciones-moviles#7]
Responsable: [Hernan David Martinez Dominguez](https://github.com/Hernan-martinezd) , [Christian Camilo Peña Florez](https://github.com/camilo2307)
Fecha entrega: 04-04-2024
Tiempo Estimado: 1 hora

**Comment by CamiloCastro-23** [comment]
se puede ver la info detallada del coleccionista y el codigo se encuentra en la rama main
