### ISSUE TITLE
Tarea: HU07 - Crear un álbum

### ISSUE THREAD

**Issue by Hernan-martinezd** [luismh92/misw4203-2024-12-ingenieria-de-software-para-aplicaciones-moviles#8]
Responsable: [Luis Alberto Mendoza Hernandez](https://github.com/luismh92)
Fecha entrega: 04-04-2024
Tiempo Estimado: 1 hora

**Comment by CamiloCastro-23** [comment]
hu implementada y se encuentra en la rama master
