### ISSUE TITLE
Tarea: HU08 - Asociar tracks con un àlbum

### ISSUE THREAD

**Issue by Hernan-martinezd** [luismh92/misw4203-2024-12-ingenieria-de-software-para-aplicaciones-moviles#9]
Responsable: [Camilo Castro Sanchez](https://github.com/CamiloCastro-MISO)
Fecha entrega: 04-04-2024
Tiempo Estimado: 1 hora

**Comment by CamiloCastro-23** [comment]
hu implementada y se encuentra en la rama master
